name: CI Android Enhanced Video Player

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.idea/**'
    branches: [ main ]
  pull_request_review:
    types:
      - submitted

concurrency:
  group: ci-check-${{ github.ref }}
  cancel-in-progress: true

jobs:

  setup-cacheable-deps:
    if: (github.event.review.state == 'approved' && !contains(github.event.pull_request.labels.*.name, 'skip-ci')) || (github.event_name == 'push')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Setup Java"
        id: cache-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        if: steps.cache-java.outputs.cache-hit != 'true'
        run: ./gradlew build

      - name: "Setup Yarn"
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

  lint:
    needs: setup-cacheable-deps
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'gradle'
      - name: Setup yarn
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Lint
        run: yarn lint

  test:
    needs: setup-cacheable-deps
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'gradle'
      - name: Setup yarn
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Test
        run: yarn test
